// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/Berlin-opendb-hack/opendb-mock/pkg/api (interfaces: Requestor)

package mock_api

import (
	gomock "github.com/golang/mock/gomock"
	http "net/http"
)

// Mock of Requestor interface
type MockRequestor struct {
	ctrl     *gomock.Controller
	recorder *_MockRequestorRecorder
}

// Recorder for MockRequestor (not exported)
type _MockRequestorRecorder struct {
	mock *MockRequestor
}

func NewMockRequestor(ctrl *gomock.Controller) *MockRequestor {
	mock := &MockRequestor{ctrl: ctrl}
	mock.recorder = &_MockRequestorRecorder{mock}
	return mock
}

func (_m *MockRequestor) EXPECT() *_MockRequestorRecorder {
	return _m.recorder
}

func (_m *MockRequestor) Do(_param0 *http.Request) (*http.Response, error) {
	ret := _m.ctrl.Call(_m, "Do", _param0)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockRequestorRecorder) Do(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Do", arg0)
}
